name: build

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  lint:
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'ci:run'
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: tetherto/oss-actions/node-base@v1
      - run: npm run lint
  test:
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'ci:run'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: tetherto/oss-actions/node-base@v1
      - run: npm test
